 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: msbuild VPKSoft.ScintillaLexers/VPKSoft.ScintillaLexers.csproj /t:restore
       - run: msbuild VPKSoft.ScintillaLexers/VPKSoft.ScintillaLexers.csproj /p:Configuration=Release
       - run: msbuild VPKSoft.ScintillaLexers.SUO/VPKSoft.ScintillaLexers.SUO.csproj /t:restore
       - run: msbuild VPKSoft.ScintillaLexers.SUO/VPKSoft.ScintillaLexers.SUO.csproj /p:Configuration=Release
# No need for bleeding edge       - run: dotnet tool install --global PowerShell
       - run: 
          name: Push to NuGet
          command: |
            NuGet-Push.ps1
            
